machine:
  node:
    version: 0.10.40

install:
  - curl https://install.meteor.com/ | sh
  - export PATH=$PATH:$HOME/.meteor
  - npm install -g jshint
  - npm install -g velocity-cli

script:
  - bash test.sh

